/* FÚTBOL DEL JUEVES · frontend */
const CFG=window.APP_CONFIG||{};
const configured=CFG.SUPABASE_URL&&!CFG.SUPABASE_URL.includes("PEGAR_")&&CFG.SUPABASE_ANON_KEY&&!CFG.SUPABASE_ANON_KEY.includes("PEGAR_");
const sb=configured?supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_ANON_KEY):null;
const POS={ARQ:"ARQ",DEF:"DEF",MED:"MED",DEL:"DEL"};
const state={user:null,players:[],matches:[],attendance:new Map(),teams:{A:[],B:[]},stats:[],currentMatch:null,generated:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const nextThursday=()=>{const d=new Date(),day=d.getDay(),add=(4-day+7)%7;d.setDate(d.getDate()+add);return d.toISOString().slice(0,10)};
const fmtDate=iso=>new Intl.DateTimeFormat("es-AR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date(iso+"T12:00:00"));
const notify=(msg,bad=false)=>{const n=$("#notice");n.textContent=msg;n.classList.remove("hidden");n.style.background=bad?"#fef2f2":"#fff7ed";n.style.color=bad?"#991b1b":"#9a3412";setTimeout(()=>n.classList.add("hidden"),4500)};
const loading=on=>$("#loading").classList.toggle("hidden",!on);
function adminUI(){const admin=!!state.user;$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!admin));$("#adminUserLabel").textContent=admin?state.user.email:"No autenticado"}
async function ensureMatch(){if(!sb){state.currentMatch={id:"demo",match_date:nextThursday(),status:"OPEN"};return}const date=nextThursday();let{data,error}=await sb.from("matches").select("*").eq("match_date",date).maybeSingle();if(error)throw error;if(!data&&state.user){const r=await sb.from("matches").insert({match_date:date,status:"OPEN"}).select().single();if(r.error)throw r.error;data=r.data}state.currentMatch=data||{id:null,match_date:date,status:"OPEN",team_a_score:null,team_b_score:null}}
async function loadAll(){loading(true);try{await ensureMatch();if(!sb){demoData();renderAll();return}const cq=state.currentMatch.id?[sb.from("attendance").select("*").eq("match_id",state.currentMatch.id),sb.from("match_players").select("*").eq("match_id",state.currentMatch.id)]:[Promise.resolve({data:[],error:null}),Promise.resolve({data:[],error:null})];const[p,m,a,t]=await Promise.all([sb.from("players").select("*").eq("active",true).order("name"),sb.from("matches").select("*").order("match_date",{ascending:false}),...cq]);if(p.error)throw p.error;if(m.error)throw m.error;if(a.error)throw a.error;if(t.error)throw t.error;state.players=p.data||[];state.matches=m.data||[];state.attendance=new Map((a.data||[]).map(x=>[x.player_id,x.confirmed]));state.teams={A:(t.data||[]).filter(x=>x.team==="A"),B:(t.data||[]).filter(x=>x.team==="B")};state.generated=state.teams.A.length===6&&state.teams.B.length===6;state.stats=await buildStats();renderAll()}catch(e){console.error(e);notify("No se pudo cargar la información: "+e.message,true)}finally{loading(false)}}
function demoData(){const names=["Juan","Pedro","Lucas","Marcos","Pablo","Diego","Guille","Fede","Nacho","Seba","Martin","Nico","Leo","Tano","Rafa","Chino","Mauri","Lucho","Dani","Javi","Ema","Ale","Fer","Coco","Gabi","Pato","Mati","Santi","Beto","Gonza"];state.players=names.map((name,i)=>({id:"demo-"+i,name,skill:2+(i%4===0?2:i%3),stamina:2+(i%4),position_1:["ARQ","DEF","MED","DEL"][i%4],position_2:["DEF","MED","DEL","DEF"][i%4],active:true}));state.attendance=new Map(state.players.slice(0,12).map(p=>[p.id,true]));state.stats=state.players.map(p=>({player_id:p.id,pj:0,pg:0,pe:0,pp:0,winrate:0,mental:0}))}
async function buildStats(){if(!sb)return state.players.map(p=>({player_id:p.id,pj:0,pg:0,pe:0,pp:0,winrate:0,mental:0}));const{data:matches,error}=await sb.from("matches").select("*").eq("status","PLAYED");if(error)throw error;const ids=(matches||[]).map(m=>m.id);if(!ids.length)return state.players.map(p=>({player_id:p.id,pj:0,pg:0,pe:0,pp:0,winrate:0,mental:0}));const{data:mp,error:e}=await sb.from("match_players").select("*").in("match_id",ids);if(e)throw e;const by={};(mp||[]).forEach(x=>(by[x.player_id]??=[]).push(x));const map={};for(const p of state.players){const games=by[p.id]||[];let pg=0,pe=0,pp=0;for(const g of games){const m=matches.find(x=>x.id===g.match_id);if(!m||m.team_a_score==null)continue;const a=m.team_a_score,b=m.team_b_score,team=g.team,win=team==="A"&&a>b||team==="B"&&b>a,draw=a===b;if(win)pg++;else if(draw)pe++;else pp++}const pj=pg+pe+pp,winrate=pj?pg/pj:0;map[p.id]={player_id:p.id,pj,pg,pe,pp,winrate,mental:(winrate-.5)*2}}return state.players.map(p=>map[p.id]||{player_id:p.id,pj:0,pg:0,pe:0,pp:0,winrate:0,mental:0})}
function rating(p){const s=state.stats.find(x=>x.player_id===p.id)||{mental:0};return p.skill*.45+p.stamina*.35+(3+s.mental)*.20}
function posSet(p){return[p.position_1,p.position_2].filter(Boolean)}
function scoreTeam(t){return t.reduce((s,p)=>s+rating(p),0)}
function counts(t){const c={ARQ:0,DEF:0,MED:0,DEL:0};t.forEach(p=>posSet(p).forEach(x=>c[x]++));return c}
function teamCost(A,B){const diff=Math.abs(scoreTeam(A)-scoreTeam(B)),ca=counts(A),cb=counts(B);let pos=0;for(const p of ["ARQ","DEF","MED","DEL"]){const d=Math.abs(ca[p]-cb[p]);pos+=d*d;if(p==="ARQ")pos+=(ca[p]===0?2:0)+(cb[p]===0?2:0)}const mental=Math.abs(A.reduce((s,p)=>s+(state.stats.find(x=>x.player_id===p.id)?.mental||0),0)-B.reduce((s,p)=>s+(state.stats.find(x=>x.player_id===p.id)?.mental||0),0));return diff*9+pos*2.2+mental*1.5}
function bestPosition(p,team){const c=counts(team);return posSet(p).sort((a,b)=>(c[a]||0)-(c[b]||0))[0]||p.position_1}
function generateTeams(){const confirmed=state.players.filter(p=>state.attendance.get(p.id));if(confirmed.length!==12){notify("Necesitás exactamente 12 confirmados.",true);return}let best=null;for(let it=0;it<2200;it++){const arr=[...confirmed].sort(()=>Math.random()-.5);let A=[],B=[];arr.sort((a,b)=>rating(b)-rating(a)).forEach((p,i)=>{const target=i%2===0?(scoreTeam(A)<=scoreTeam(B)?A:B):(scoreTeam(A)<=scoreTeam(B)?B:A);target.push(p)});for(let k=0;k<10;k++){const i=Math.floor(Math.random()*6),j=Math.floor(Math.random()*6),cost=teamCost(A,B);[A[i],B[j]]=[B[j],A[i]];if(teamCost(A,B)>cost&&Math.random()>.12)[A[i],B[j]]=[B[j],A[i]]}const c=teamCost(A,B);if(!best||c<best.c)best={A:[...A],B:[...B],c}}state.teams={A:best.A.map(p=>({player_id:p.id,team:"A",position:bestPosition(p,best.A)})),B:best.B.map(p=>({player_id:p.id,team:"B",position:bestPosition(p,best.B)}))};state.generated=true;renderTeams();if(state.user)saveTeams().catch(e=>notify(e.message,true))}
async function saveTeams(){if(!sb||!state.user||!state.currentMatch?.id)return;const rows=[...state.teams.A,...state.teams.B].map(x=>({match_id:state.currentMatch.id,player_id:x.player_id,team:x.team,position:x.position}));let r=await sb.from("match_players").delete().eq("match_id",state.currentMatch.id);if(r.error)throw r.error;r=await sb.from("match_players").insert(rows);if(r.error)throw r.error}
async function saveAttendance(){if(!sb||!state.user||!state.currentMatch?.id)return;const rows=state.players.map(p=>({match_id:state.currentMatch.id,player_id:p.id,confirmed:!!state.attendance.get(p.id)}));const{error}=await sb.from("attendance").upsert(rows);if(error)throw error}
async function saveResult(){const a=parseInt($("#scoreAInput").value),b=parseInt($("#scoreBInput").value);if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0){notify("Cargá dos resultados válidos.",true);return}if(!state.generated){notify("Primero armá los equipos.",true);return}if(!sb||!state.user||!state.currentMatch?.id){notify("Iniciá sesión como administrador primero.",true);return}loading(true);try{const{error}=await sb.from("matches").update({team_a_score:a,team_b_score:b,status:"PLAYED",updated_at:new Date().toISOString()}).eq("id",state.currentMatch.id);if(error)throw error;state.currentMatch.team_a_score=a;state.currentMatch.team_b_score=b;state.currentMatch.status="PLAYED";state.stats=await buildStats();renderAll();notify("Resultado guardado y estadísticas actualizadas.")}catch(e){notify(e.message,true)}finally{loading(false)}}
function renderAll(){renderHeader();renderAttendance();renderTeams();renderResult();renderStats();renderPlayers();renderHistory();adminUI()}
function renderHistory(){const sel=$("#historyMatchSelect");if(!sel||!state.user)return;const played=(state.matches||[]).filter(m=>m.id!==state.currentMatch.id).slice(0,20);sel.innerHTML=played.length?played.map(m=>`<option value="${m.id}">${fmtDate(m.match_date)}${m.status==="PLAYED"?" · "+m.team_a_score+"-"+m.team_b_score:" · pendiente"}</option>`).join(""):`<option value="">No hay partidos anteriores</option>`;const m=played[0];if(m){$("#historyScoreA").value=m.team_a_score??"";$("#historyScoreB").value=m.team_b_score??""}}
function renderHeader(){$("#matchDateLabel").textContent=fmtDate(state.currentMatch.match_date);const n=state.players.filter(p=>state.attendance.get(p.id)).length;$("#attendanceCount").textContent=n;$("#confirmedPill").textContent=`${n} / 12`;$("#matchStatusLabel").textContent=state.currentMatch.status==="PLAYED"?"Partido jugado":"Convocatoria abierta"}
function renderAttendance(){const list=$("#attendanceList");list.innerHTML="";state.players.forEach(p=>{const selected=!!state.attendance.get(p.id),row=document.createElement("label");row.className="player-row "+(selected?"selected":"");row.innerHTML=`<input class="check" type="checkbox" ${selected?"checked":""} ${state.user?"":"disabled"}><span class="avatar">${initials(p.name)}</span><span class="player-main"><b>${esc(p.name)}</b><span>${p.position_1}${p.position_2?" · "+p.position_2:""} · Nivel ${p.skill} · Stamina ${p.stamina}</span></span><span class="rating">${rating(p).toFixed(1)}</span>`;row.querySelector("input").onchange=async e=>{if(e.target.checked&&state.players.filter(x=>state.attendance.get(x.id)).length>=12){e.target.checked=false;notify("Ya hay 12 confirmados. Desmarcá a alguien primero.",true);return}state.attendance.set(p.id,e.target.checked);renderHeader();try{await saveAttendance()}catch(err){notify(err.message,true)}};list.appendChild(row)})}
function playerById(id){return state.players.find(p=>p.id===id)}
function renderTeams(){$("#teamsEmpty").classList.toggle("hidden",state.generated);$("#teamsWrap").classList.toggle("hidden",!state.generated);if(!state.generated){$("#balancePill").textContent="—";return}const A=state.teams.A.map(x=>playerById(x.player_id)).filter(Boolean),B=state.teams.B.map(x=>playerById(x.player_id)).filter(Boolean);$("#scoreA").textContent=scoreTeam(A).toFixed(1);$("#scoreB").textContent=scoreTeam(B).toFixed(1);$("#balancePill").textContent=`Δ ${Math.abs(scoreTeam(A)-scoreTeam(B)).toFixed(2)}`;const render=(el,arr,team)=>{$(el).innerHTML=arr.map(p=>{const rec=state.teams[team].find(x=>x.player_id===p.id);return`<div class="team-player"><span class="pos">${rec?.position||p.position_1}</span><span class="player-main"><b>${esc(p.name)}</b><span>Nivel ${p.skill} · Stamina ${p.stamina}</span></span></div>`}).join("")};render("#teamAList",A,"A");render("#teamBList",B,"B")}
function renderResult(){const a=state.currentMatch.team_a_score,b=state.currentMatch.team_b_score;$("#resultView").textContent=a==null?"—":`🟩 ${a}  —  ${b} 🟨`;$("#scoreAInput").value=a??"";$("#scoreBInput").value=b??""}
function renderStats(){$("#statsTable").innerHTML=`<table class="stats-table"><thead><tr><th>#</th><th>Jugador</th><th>PJ</th><th>PG</th><th>PE</th><th>PP</th><th>% Vic</th></tr></thead><tbody>${[...state.stats].sort((a,b)=>b.winrate-a.winrate||b.pg-a.pg||b.pj-a.pj).map((s,i)=>{const p=playerById(s.player_id);return p?`<tr><td class="rank">${i+1}</td><td>${esc(p.name)}</td><td>${s.pj}</td><td>${s.pg}</td><td>${s.pe}</td><td>${s.pp}</td><td class="winrate">${(s.winrate*100).toFixed(1)}%</td></tr>`:""}).join("")}</tbody></table>`;const cutoff=new Date();cutoff.setHours(0,0,0,0);cutoff.setDate(cutoff.getDate()-30);const recentIds=new Set((state.matches||[]).filter(m=>m.status==="PLAYED"&&m.match_date&&new Date(m.match_date+"T12:00:00")>=cutoff).map(m=>m.id));const recent={};for(const s of state.stats)recent[s.player_id]={player_id:s.player_id,pj:0,pg:0,pe:0,pp:0};if(sb&&recentIds.size){sb.from("match_players").select("*").in("match_id",[...recentIds]).then(({data})=>{for(const g of data||[]){const m=state.matches.find(x=>x.id===g.match_id);if(!m||m.team_a_score==null)continue;const r=recent[g.player_id]||(recent[g.player_id]={player_id:g.player_id,pj:0,pg:0,pe:0,pp:0}),win=g.team==="A"&&m.team_a_score>m.team_b_score||g.team==="B"&&m.team_b_score>m.team_a_score,draw=m.team_a_score===m.team_b_score;r.pj++;if(win)r.pg++;else if(draw)r.pe++;else r.pp}const rec=Object.values(recent).filter(x=>x.pj>0).sort((a,b)=>b.pg/b.pj-a.pg/a.pj||b.pg-a.pg||b.pj-a.pj),mvp=rec[0];$("#mvpBox").innerHTML=mvp?`${esc(playerById(mvp.player_id)?.name)}<small>${(mvp.pg/mvp.pj*100).toFixed(1)}% de victorias · ${mvp.pg} PG en ${mvp.pj} PJ</small>`:"Sin partidos en los últimos 30 días."}).catch(()=>$("#mvpBox").textContent="No se pudo calcular el MVP reciente.")}else $("#mvpBox").textContent="Sin partidos en los últimos 30 días.";const eligible=state.stats.filter(s=>s.pj>0),wall=[...eligible].sort((a,b)=>b.pg-a.pg||b.winrate-a.winrate)[0];$("#wallBox").innerHTML=wall?`${esc(playerById(wall.player_id)?.name)}<small>${wall.pg} victorias · ${wall.pj} partidos · ${(wall.winrate*100).toFixed(1)}% Vic</small>`:"Todavía no hay partidos registrados."}
function renderPlayers(){$("#playersGrid").innerHTML=state.players.map(p=>`<div class="player-card"><div class="player-card-head"><span class="avatar">${initials(p.name)}</span><div><h3>${esc(p.name)}</h3><p>${p.position_1}${p.position_2?" · "+p.position_2:""}</p></div>${state.user?`<button class="icon-btn edit-player" data-id="${p.id}" style="margin-left:auto;color:#111827;background:#eef2f7;border:0">✎</button>`:""}</div><div class="bars"><div class="bar-row"><span>Habilidad</span><div class="bar"><i style="width:${p.skill*20}%"></i></div><b>${p.skill}</b></div><div class="bar-row"><span>Stamina</span><div class="bar"><i style="width:${p.stamina*20}%"></i></div><b>${p.stamina}</b></div></div></div>`).join("");$$('.edit-player').forEach(b=>b.onclick=()=>openPlayer(b.dataset.id))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function login(){const email=$("#email").value,password=$("#password").value;$("#loginError").textContent="";if(!sb){$("#loginError").textContent="La app está en modo demo.";return}const{data,error}=await sb.auth.signInWithPassword({email,password});if(error){$("#loginError").textContent=error.message;return}state.user=data.user;$("#loginModal").classList.add("hidden");adminUI();await loadAll()}
async function logout(){if(sb)await sb.auth.signOut();state.user=null;$("#adminDrawer").classList.add("hidden");adminUI();await loadAll()}
async function savePlayer(e){e.preventDefault();if(!sb||!state.user){notify("Necesitás iniciar sesión.",true);return}const id=$("#playerId").value,payload={name:$("#playerName").value.trim(),skill:+$("#playerSkill").value,stamina:+$("#playerStamina").value,position_1:$("#playerPos1").value,position_2:$("#playerPos2").value||null,active:true};loading(true);try{const q=id?sb.from("players").update(payload).eq("id",id):sb.from("players").insert(payload),{error}=await q;if(error)throw error;$("#playerModal").classList.add("hidden");await loadAll();notify("Jugador guardado.")}catch(err){notify(err.message,true)}finally{loading(false)}}
function openPlayer(id=null){$("#playerForm").reset();$("#playerId").value=id||"";$("#playerPos1").innerHTML=Object.values(POS).map(x=>`<option>${x}</option>`).join("");$("#playerPos2").innerHTML=`<option value="">Sin segunda posición</option>`+Object.values(POS).map(x=>`<option>${x}</option>`).join("");if(id){const p=playerById(id);$("#playerModalTitle").textContent="Editar jugador";$("#playerName").value=p.name;$("#playerSkill").value=p.skill;$("#playerStamina").value=p.stamina;$("#playerPos1").value=p.position_1;$("#playerPos2").value=p.position_2||""}else $("#playerModalTitle").textContent="Nuevo jugador";$("#playerModal").classList.remove("hidden")}
function copyWhatsApp(){if(!state.generated)return;const line=(x,i)=>{const p=playerById(x.player_id);return`${i+1}. ${p.name} (${x.position||p.position_1})`};const text=`⚽ *FÚTBOL DEL JUEVES* ⚽\n📅 ${fmtDate(state.currentMatch.match_date)}\n\n🟩 *EQUIPO A:*\n${state.teams.A.map(line).join("\n")}\n\n🟨 *EQUIPO B:*\n${state.teams.B.map(line).join("\n")}\n\n🔥 ¡Nos vemos en la cancha!`;navigator.clipboard.writeText(text).then(()=>notify("Texto copiado. Pegalo en WhatsApp.")).catch(()=>prompt("Copiá este texto:",text))}
function openSwap(){if(!state.generated)return;$("#swapA").innerHTML=state.teams.A.map(x=>`<option value="${x.player_id}">${esc(playerById(x.player_id).name)}</option>`).join("");$("#swapB").innerHTML=state.teams.B.map(x=>`<option value="${x.player_id}">${esc(playerById(x.player_id).name)}</option>`).join("");$("#manualSwapModal").classList.remove("hidden")}
async function swapPlayers(){const a=$("#swapA").value,b=$("#swapB").value,ai=state.teams.A.findIndex(x=>x.player_id===a),bi=state.teams.B.findIndex(x=>x.player_id===b);[state.teams.A[ai],state.teams.B[bi]]=[state.teams.B[bi],state.teams.A[ai]];state.teams.A[ai].team="A";state.teams.B[bi].team="B";$("#manualSwapModal").classList.add("hidden");renderTeams();try{await saveTeams();notify("Jugadores intercambiados.")}catch(e){notify(e.message,true)}}
async function backup(){if(!sb||!state.user)return;loading(true);try{const[p,m,a,t]=await Promise.all([sb.from("players").select("*"),sb.from("matches").select("*"),sb.from("attendance").select("*"),sb.from("match_players").select("*")]),data={version:1,exported_at:new Date().toISOString(),players:p.data,matches:m.data,attendance:a.data,match_players:t.data},blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),aEl=document.createElement("a");aEl.href=url;aEl.download=`futbol-jueves-backup-${new Date().toISOString().slice(0,10)}.json`;aEl.click();URL.revokeObjectURL(url)}catch(e){notify(e.message,true)}finally{loading(false)}}
async function importBackup(file){if(!sb||!state.user)return;let data;try{data=JSON.parse(await file.text())}catch(e){notify("El archivo no es JSON válido.",true);return}if(!data.players||!data.matches){notify("Backup inválido.",true);return}if(!confirm("Esto insertará los datos del backup. ¿Continuar?"))return;loading(true);try{for(const[k,table]of[["players","players"],["matches","matches"],["attendance","attendance"],["match_players","match_players"]])if(data[k]?.length){const r=await sb.from(table).upsert(data[k]);if(r.error)throw r.error}await loadAll();notify("Backup importado.")}catch(e){notify(e.message,true)}finally{loading(false)}}
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$("#tab-"+b.dataset.tab).classList.add('active')});
$("#adminBtn").onclick=()=>state.user?$("#adminDrawer").classList.remove("hidden"):$("#loginModal").classList.remove("hidden");$("#loginForm").onsubmit=e=>{e.preventDefault();login()};$("#logoutBtn").onclick=logout;$("#refreshBtn").onclick=loadAll;$("#generateBtn").onclick=generateTeams;$("#shuffleBtn").onclick=generateTeams;$("#copyBtn").onclick=copyWhatsApp;$("#addPlayerBtn").onclick=()=>openPlayer();$("#playerForm").onsubmit=savePlayer;$("#saveResultBtn").onclick=saveResult;$("#clearAttendanceBtn").onclick=async()=>{if(!confirm("¿Limpiar convocatoria?"))return;state.attendance=new Map();await saveAttendance();renderAll()};$("#manualSwapBtn").onclick=openSwap;$("#swapBtn").onclick=swapPlayers;$("#historyMatchSelect").onchange=()=>{const m=state.matches.find(x=>x.id===$("#historyMatchSelect").value);if(m){$("#historyScoreA").value=m.team_a_score??"";$("#historyScoreB").value=m.team_b_score??""}};$("#historySaveBtn").onclick=async()=>{const id=$("#historyMatchSelect").value,a=parseInt($("#historyScoreA").value),b=parseInt($("#historyScoreB").value);if(!id||!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0){notify("Elegí un partido y cargá un resultado válido.",true);return}loading(true);try{const r=await sb.from("matches").update({team_a_score:a,team_b_score:b,status:"PLAYED",updated_at:new Date().toISOString()}).eq("id",id);if(r.error)throw r.error;state.matches=state.matches.map(m=>m.id===id?{...m,team_a_score:a,team_b_score:b,status:"PLAYED"}:m);state.stats=await buildStats();renderAll();notify("Resultado histórico guardado.")}catch(e){notify(e.message,true)}finally{loading(false)}};$("#backupBtn").onclick=backup;$("#importInput").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$$('[data-close]').forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.add("hidden"));document.addEventListener("keydown",e=>{if(e.key==="Escape")$$('.modal,.drawer').forEach(x=>x.classList.add('hidden'))});
if(sb){sb.auth.getSession().then(({data})=>{state.user=data.session?.user||null;adminUI();loadAll()});sb.auth.onAuthStateChange((_event,session)=>{state.user=session?.user||null;adminUI()})}else{notify("Modo demo: conectá Supabase para guardar datos online.");loadAll()}